- asteval/asteval.py
`__builtins__` behaves slightly different on pypy vs CPython:
- on CPython: the docs say "The value of `__builtins__` is normally either this module or the value of this module’s `__dict__` attribute". This is affected by whether this is the `__main__` module.
- on pypy: this is always the module.
When it's the module, the dict lives inside of the __dict__ attribute
I've tested this by running the unittests on Python 2 + Python 3.
Tests don't pass yet on PyPy (due to NumPy being missing), but the non-numpy ones do pass
> Improve pypy compatability

- asteval/__init__.py
See e.g. [`__all__` in the stdlib subprocess module](https://hg.python.org/cpython/file/3.5/Lib/subprocess.py#l459).
Originally reported as ipython/ipython#9678.
> __all__ should list strings of names, not objects

- asteval/asteval.py
Hi,
This is a really nice project. Thank you :)
This is something I faced when I wanted support a smaller subset of `supported_nodes` (as mentioned in Issue #13 ). 
```
In [1]: from asteval.asteval import Interpreter
In [2]: reqd_entries = ['binop','boolop','compare','expr','module','name','num','str','nameconstant','unaryop']
In [3]: Interpreter.supported_nodes = tuple(reqd_entries)
In [4]: asteval = Interpreter()
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-92399253e0b7> in <module>()
----> 1 asteval = Interpreter()
/Users/nithin/myspace/asteval/asteval/asteval.py in __init__(self, symtable, writer, use_numpy, err_writer, max_time)
123
124         # to rationalize …
```
> Add check for 'try' before assigning it

- asteval/asteval.py
- asteval/astutils.py
- tests/testsuite.py
This attempts to address #32.  It may not be complete, but I think it addresses the most important point of that error -- that Procedure properties, including `body` can be overwritten.
> Safer procedures

- asteval/asteval.py
Currently any user-defined methods that raise an exception inside of the interpreter are re-raised by the `raise_exception` function without the message from the original exception. See below for example:
```
In [1]: import asteval
In [2]: def foo():
...:     raise Exception("Example error")
...:
In [3]: interpreter = asteval.Interpreter(usersyms={"foo": foo})
In [4]: interpreter("foo()")
Exception
foo()
Error running <function foo at 0x07D9E030>
```
Having the original exception message is important for debugging, so I've added the original error message to the call to `raise_exception`. In addition, I think having the function name is more useful than having the whole function, so I also changed that. Now an error message will look like this:
```
In [1]: import asteval
In [2]: def …
```
> Include called function's exception message on failed on_call

- asteval/asteval.py
The error discussed in #42 was due to the `on_call` function calling either a function or a `Procedure` object. While functions have a `__name__` attribute, `Procedure` objects did not, which caused a `AttributeError` to be raised whenever an exception occurred in the evaluated line (see [this](https://travis-ci.org/newville/asteval/builds/416559346?utm_source=github_status&utm_medium=notification) test failure).
I've remedied this by giving `Procedure` objects a `__name__` attribute. I'll acknowledge that this is a bit redundant since they already have a `name` attribute, so we have several options on how we'd want to proceed:
* Leave it the way it is
* Convert all `Procedure.name` references to `Procedure.__name__`
* Add logic into the exception handler in `on_call` to differentiate …
> Give Procedure objects a __name__ attribute

- asteval/asteval.py
- tests/test_asteval.py
The symblacklist is a set of names that can not be assigned to (count as reserved)
blacklist_builtins will, if set, put all names in the initial symtable in the symblacklist, thereby disallowing users to overwrite those.
This will be especially useful if the same Interpreter is used by multiple users:
With this the users can use each others functions, but they will not be able to break the builtin functions.
'buildin' here means any name that is in the initial symtable
I have not yet ran the tests or created tests for these options because of issue #44 
When testing manually it seemed to work.
> Added options symblacklist and blacklist_builtins

- asteval/asteval.py
This is probably the minimum required changes to prevent exponential or quadratic growth of self.error_msg in recursion
> don't copy self.error_msg into itself

- asteval/asteval.py
- tests/test_asteval.py
In the current code, when catching an exception in a try block, the rest of the try block will still be executed.
For example:
try:
raise Exception("something wrong!")
print("I'm fine")
except:
print("caught an error")
results in:
caught an error
I'm fine
This shouldn't happen. The "I'm fine" print should not be executed.
This is one of the problems mentioned in #52 
This PR fixes that and adds a test for this behaviour
> don't continue a try block after an error is caught

- asteval/astutils.py
- tests/test_asteval.py
The safe functions `safe_pow` and `safe_lshift` assumed that the exponent was a numerical value (int, float, etc.). The if statements (`if exp > MAX_EXPONENT:`) failed when a numpy array was passed for the exponent: 
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`
This change allows for numpy arrays to be passed as the exponent in these operations without the conditional statement failing. Instead of comparing the variable itself with `MAX_<>`, it compares the max value (using `numpy.nanmax`) with `MAX_<>`.
> Safe numpy

- asteval/asteval.py
- tests/test_asteval.py
In our local usage of asteval, we encountered intermittent bugs where asteval claimed functions were timing out after 86400 seconds. The python server executing these asteval interpreters had been up around 10 minutes, indicating something was very much awry.
As I was unable to reproduce manually, I'm unsure of the underlying cause. It's possible this is due to an unusual setup with time zones in our docker containers, as we've purged all the locale information. 
That said, removing the relevant code from our local fork of asteval was sufficient to stop this problem. I am proposing deprecating this feature now for the sake of others who may encounter this ill-defined bug.
> [Proposed] deprecate max run time now rather than later

- asteval/asteval.py
I has been using this package for a while now, but when I was initially scoping it out, I was running into Exception recursion errors similar to what @bek0s was running into on https://github.com/newville/asteval/issues/63 this morning. I had been running a fork for my application, but I thought it was a good time to propose bringing this patch into master.
The root of the issue is that `run` can be called on each node recursively, so if there's an exception, `raise_exception` can be called many times. My proposal here is to change the behavior of the `run` method so that it immediately raises when the first error occurs. I can't think of a case where you would want to catch multiple exceptions in the `error` list, nor can I see anything in the tests that indicate this is an intended …
> Raise immediately on the first error

- asteval/asteval.py
- tests/test_asteval.py
I ran into an issue recently where I passed in a partial function into the symbol table, and then ran a method that raised an `Exception`. Instead of raising the `Exception` I expected, I instead encountered a `AttributeError` due to `functools.partial` objects not having a `__name__` attribute. This is best illustrated by example:
Before:
```python
In [1]: from functools import partial
In [2]: import math
In [3]: import asteval
In [4]: aeval=asteval.Interpreter()
In [5]: aeval.symtable["sqrt"] = partial(math.sqrt)
In [6]: aeval("sqrt(-1)")
AttributeError
sqrt(-1)
'functools.partial' object has no attribute '__name__'
```
After:
```python
In [1]: from functools import partial
In [2]: import math
In [3]: import asteval
In [4]: aeval=asteval.Interpreter()
In [5]: aeval.symtable["sqrt"] = …
```
> Don't raise AttributeError when using partials

- asteval/asteval.py
- tests/test_asteval.py
Currently, if you raise an assertion error, you get a message like this:
```
In [1]: interpreter.eval("assert False, 'test'")
AssertionError: <_ast.Str object at 0x00FBEC90>
```
Ideally, you would get:
```
In [1]: interpreter.eval("assert False, 'test'")
AssertionError: test
```
This PR fixes that problem by pulling the string out of the `_ast.Str` object
> Correct assertion message

- asteval/astutils.py
This PR removes deprecated functions/aliases when using NumPy v1.20.0 ; see the [release notes](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations) for more information.
Quite possibly there is a more elegant way of doing this, but in my testing for `lmfit` it works as expected.
> MAINT: remove deprecated aliases when using NumPy v1.20.0

- asteval/asteval.py
- asteval/astutils.py
- doc/motivation.rst
See #86 for motivation and discussion.   This removes access to all `__dunder__` attributes.
> deny access to any __dunder__ attributes

- asteval/asteval.py
- asteval/astutils.py
The `Interpreter` is constructed many times when fitting with `lmfit`. This PR improves performance by
* Taking the calculation of the number version out of the loop
* Changing the order of the check for `no_deepcopy`
Current master branch:
```
%timeit Interpreter()
364 µs ± 21.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
``` 
With this PR
``` 
%timeit Interpreter()
271 µs ± 23.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
``` 
@newville
> Performance of Interpreter construction

- pyproject.toml
The dependency on `wheel` is redundant since setuptools' build backend
adds it automatically.  Listing it in documentation has been a mistake
and it has been fixed since.  See:
https://github.com/pypa/setuptools/commit/f7d30a9529378cf69054b5176249e5457aaf640a
> Remove redundant wheel dependency from pyproject.toml

- asteval/astutils.py
This is a continuation of #104. The `Interpreter` is constructed many times when fitting with lmfit and this calls `make_symbol_table`. This PR improves performance by taking many checks on the valid symbols in `math`, `sympy` and `builtins` out of the function.
Master:
```
In [2]: %timeit make_symbol_table()
172 µs ± 3.16 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
This PR:
```
In [59]: %timeit make_symbol_table()
11.3 µs ± 421 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
Note: the (slighty) reduced coverage is in a part that was only modified by autopep and branches where numpy is not installed, but it seems numpy is installed when running coverage. If it is required to fix this, please suggest how to approach this.
> Improve performance of make_symbol_table

- asteval/asteval.py
This takes the recent addition of multiple list comprehension, and recurses on it rather than rely on a hard-coded solution. This should remove the limitation of 4 for loops. 
I can't pretend to understand a lot about this library, so please let me know if this has any obvious issues I haven't spotted! I ran some tests locally and it seems to work well, though.
> Deal with multiple list comprehension recursively.

- asteval/astutils.py
In numpy 1.24 a couple of aliases have been deprecated. In this PR we add the deprecated aliases to the list so they are not added to the asteval symbol table (and they do not generate warnings when asteval is used with numpy 1.24).
If these aliases are still in use and we do not want to remove them, we could create a PR what suppresses the warnings during addition for these elements. 
@newville
> Fix numpy 1.24 deprecation warnings

- asteval/astutils.py
In this PR we add four attributes that have been deprecated in numpy 2.0. Three out of the four have already been deprecated before, but are not selected because the statement `if int(numpy_version[0]) == 1 and int(numpy_version[1]) >= 20` is false for numpy 2.0.
Numpy 2.0 is scheduled to be released end of 2023, see https://github.com/numpy/numpy/issues/24300
> Add deprecations for numpy 2.0

- asteval/asteval.py
Fixes https://github.com/lmfit/asteval/issues/129
@newville could you take a look please?
> fix NameError handling in expression code

- asteval/astutils.py
- tests/test_asteval.py
This is intended to address the security vulnerability in https://github.com/lmfit/asteval/security/advisories/GHSA-vp47-9734-prjw
by making all attributes of Procedure use "dunder names", so that they are viewed as unsafe from within the asteval Interpreter.
> Fix unsafe procedures

- asteval/asteval.py
- tests/test_asteval.py
This pr added the missing lineno in augassign operation. The error message should be more precise with this fix.
> fix augassign which has no line number
